### ISSUE TITLE
Only use alphanumeric characters in profile name

### ISSUE THREAD

**Issue by MaartenW** [gl-inet/imagebuilder#11]
If you use a profile name with an underscore in it, expect strange results.

**Comment by Hoff-GLiNet** [comment]
Hi MaartenW, Sorry for the late reply.
Can you give me more information? For example sereenshot?

**Comment by MaartenW** [comment]
I'm sorry, I don't have a screenshot.
Please just try adding the name of a profile in the `customize.json` (e.g. `"mifi_compact"`) and you will see the results when building.
(I think there's some magic going on with the naming and underscores during the build phase)

**Comment by Hoff-GLiNet** [comment]
Hi MaartenW,I have tested **mifi_compact**,it is ok.
Here is a gif picture:https://github.com/Hoff-GLiNet/test

**Comment by MaartenW** [comment]
Ok, I'll close the issue. When I have time to verify and have a different experience, I'll reopen.
Thanks for your effort!
