### ISSUE TITLE
Cannot build image for SFT1200

### ISSUE THREAD

**Issue by bittervan** [gl-inet/imagebuilder#19]
using `python2.7 gl_image -p sft1200` to build the image results in 

```
 * opkg_install_cmd: Cannot install package gl-init-portal.
 * opkg_install_cmd: Cannot install package gl-siderouter.
```

**Comment by Qinka** [comment]
Same problem.

But, after I change glinet to tag [sft1200_v3.212_20220530](https://github.com/gl-inet/glinet/tree/sft1200_v3.212_20220530), it success.

**Comment by bittervan** [comment]
> Qinka

Thanks a lot. But I've get it refunded after so much crash using xl2tpd..
