### ISSUE TITLE
S1300 Base image and Bluetooth

### ISSUE THREAD

**Issue by ibnbd** [gl-inet/imagebuilder#3]
@LancerSky S1300  GL.iNet base image still based on OpenWRT 15, any plans to upgrade to the latest? 

Bluetooth still doesn't works on my S1300, every time I try to scan I get error. I bought this device during super early bird, in case the hardware was different.

Also non GL.iNet packages at `http://download.gl-inet.com/releases/packages-3.x/ipq40xx/` are really old.

Thank You

**Comment by lancersky** [comment]
Hi, Because of using QCA WifiSon, there are currently no upgrade plans.

**Comment by HarvsG** [comment]
@LancerSky How could I build my own B1300 or S1300 image based on OpenWRT 19.07. Accepting there would not be QCA WifiSON
