### ISSUE TITLE
Where can i find the list of packages that can be used with `--extra`?

### ISSUE THREAD

**Issue by lestephane** [gl-inet/imagebuilder#5]
Maybe the README should include that information

**Comment by lancersky** [comment]
Hi, I think you should know what package are you want to install.
And the list of packages you can find from https://openwrt.org/packages/start
Thanks.

**Comment by lancersky** [comment]
Hi, I think you should know what package are you want to install.
And the list of packages you can find from https://openwrt.org/packages/start
Thanks.

**Comment by lestephane** [comment]
Thanks LancerSky, https://openwrt.org/packages/start is the answer I was looking for.
The link should be added to the README or the command help to point people who are
not familiar with the whole openwrt ecosystem in the right direction.

In any case, closing this issue since It's now resolved for me.

**Comment by lancersky** [comment]
Thanks a lot. We will optimize it.
