### ISSUE TITLE
Customization files fails to load

### ISSUE THREAD

**Issue by thinkopensource** [gl-inet/imagebuilder#6]
Hi
Im working with a AR150 to customize image with some extra packages and I found that customization.json is not accepting files instruction. code is

> `"profile": "gl-ar150",`
>  ` "version": "3.027",`
>   `"imagebuilder": "3.1/openwrt-imagebuilder-ar71xx-generic_3.1",`
>   `"packages": "gl-base-files-ar $basic $vpn $storage $usb $glinet tcpdump logrotate curl gawk",`
>   `"files": "/etc/config/firewall"`
> 

file "firewall" is in $ROOT_PATH_OF_IMAGEBUILDER/etc/config

There is no error message, but file is not loaded.

**Comment by thinkopensource** [comment]
I understand that I need to create a folder "files" inside root tree folder? I tested and fails anyway

**Comment by lancersky** [comment]
Do you want to custom the firewall? 
Firstly, you need to create files folder in 'imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/files'. So you can add your etc folder to the files folder.
Lastly, The configuration file looks like this. "files": "imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/files"

**Comment by thinkopensource** [comment]
Sorry but this not works. Are you sure that files reference inside customize.json needs to be:

`"files": "imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/files"`

Using same logic that "imagebuilder" reference this option needs to be

`"files": "3.1/openwrt-imagebuilder-ar71xx-generic_3.1/files"`

**Comment by lancersky** [comment]
I have make a test as following.
mkdir -p imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/files/etc/config/
vim imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/files/etc/config/test 
vim customize.json add files path,
          "ar150": {
              "profile": "gl-ar150",
              "version": "3.027",
              "imagebuilder": "3.1/openwrt-imagebuilder-ar71xx-generic_3.1",
              "packages": "gl-base-files-ar $basic $vpn $storage $usb $glinet",
              "files": "imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/files"
          },
./gl_image -p ar150 -c customize.json
At last, you can find test file in root system.
imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/build_dir/target-mips_24kc_musl/root-ar71xx/etc/config/test

**Comment by thinkopensource** [comment]
After check with a clean installation I did your test and is correct, new files are copied to GL, but not config files because seems that are generated after to copy (you can see looking modification date). In this case using this function I can't change configuration, only send new files. exist any form to do this?

**Comment by lancersky** [comment]
Hi, please check again. I operate in the imagebuilder root directory.
$ ls -l
total 64
drwxrwxr-x 5 lancer lancer  4096 2月  14 19:40 bin
drwxrwxr-x 2 lancer lancer  4096 2月   6 12:19 config
-rwxrwxr-x 1 lancer lancer  7275 2月  14 20:10 customize.json
-rw-rw-r-- 1 lancer lancer   285 2月   6 12:19 Dockerfile
drwxrwxr-x 3 lancer lancer  4096 2月  14 19:56 files
-rwxrwxr-x 1 lancer lancer 20807 2月   7 10:10 gl_image
drwxrwxr-x 7 lancer lancer  4096 2月   6 12:21 glinet
drwxrwxr-x 4 lancer lancer  4096 2月  14 19:52 imagebuilder
-rwxrwxr-x 1 lancer lancer  6573 2月  14 20:09 README.md

##create files/etc/config folder
$ mkdir -p files/etc/config
##write test phrase to files/etc/config/firewall
$ echo "test file" > files/etc/config/firewall

##vim customize.json to add files path
"ar150": {
    "profile": "gl-ar150",
    "version": "3.027",
    "imagebuilder": "3.1/openwrt-imagebuilder-ar71xx-generic_3.1",
    "packages": "gl-base-files-ar $basic $vpn $storage $usb $glinet",                                           
    "files": "files"
},
## compile 
$ ./gl_image -p ar150 -c customize.json

##you can check the build dir contain test file
$ cat imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/build_dir/target-mips_24kc_musl/root-ar71xx/etc/config/firewall   
test file

##you can extrect firmware to check again
$ binwalk -e openwrt-ar150-3.027-0215_customize.bin
$ cat _openwrt-ar150-3.027-0215_customize.bin.extracted/squashfs-root/etc/config/firewall 
test file
Thanks.

**Comment by thinkopensource** [comment]
Hi 

I compiled how you said but checking 

cd  imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/build_dir/target-mips_24kc_musl/root-ar71xx/etc/config

not appears any file, so the line 

"files": "files" 

needs to be 

"files": "imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/files"

Anyway, the problem continue, because Im not saying that files are not copied, script seems that copy files BEFORE to config, and all files are removed when starts automatic configuration.

**Comment by thinkopensource** [comment]
So finally, where I can setup config daemons ? Im refering the folder 

./gl_imagebuilder/imagebuilder/3.1/openwrt-imagebuilder-ar71xx-generic_3.1/build_dir/target-mips_24kc_musl/root-ar71xx/etc/config/

**Comment by lancersky** [comment]
The files point to a path. That is not a problem. Colud you show me your operate step by step?

**Comment by thinkopensource** [comment]
yes, files point to a path, and I can send files, but my problem is justly that I can't change default parameters inside this image because I couldn't find where openwrt made first setup inside firewall, generating file /etc/config/firewall.

**Comment by thinkopensource** [comment]
Hi
to update this thread and close, the problem was the use of sysupgrade command. To remove old configurations when update firmware you need to use

$ sysupgrade -n ./image.bin

I recommend to include some example about "files" option.

Thanks
