### ISSUE TITLE
Help Question: Customized Web Interface (Admin Panel) 

### ISSUE THREAD

**Issue by horeeorg** [gl-inet/imagebuilder#7]
Hi we would like to customized the Web Interface for Admin Panel, 
can you point us, how to do it? 

Or what repository for the source code ? Is it in the glinet (ipk package file) ?

Or Is it propietary of GL-Inet ?

**Comment by lancersky** [comment]
Yeah, the Web Interface is placed in the glinet repository name of gl-ui_xxx.ipk. You can extract and change it. Thanks.

**Comment by horeeorg** [comment]
okay got it, thanks
